## Exercise 04

__1.__ For the following three NumPy arrays:

In [4]:
import numpy as np

a = np.array([1, 3, 5, 7])
b = np.array([8, 7, 5, 4])
c = np.array([0, 9,-6,-8])

Put them in a single array and make them columns in the new array.

In [ ]:
d=

In [6]:
d

[[ 1  8  0]
 [ 3  7  9]
 [ 5  5 -6]
 [ 7  4 -8]]


__3.__  Write a Python script to read the "TestData.txt" file under the folder to "./data" into a three NumPy arrays with the variable names `f`, `a`, `da` for the frequency, amplitude, and amplitude error.

In [2]:
%less ./data/TestData.txt

Date: 2013-09-16
Data taken by Liam and Selena
frequency (Hz) amplitude (mm) amp error (mm)
 0.7500 13.52         0.32
 1.7885 12.11         0.92
 2.8269 14.27         0.73
 3.8654 16.60         2.06
 4.9038 22.91         1.75
 5.9423 35.28         0.91
 6.9808 60.99         0.99
 8.0192 33.38         0.36
 9.0577 17.78         2.32
10.0962 10.99         0.21
11.1346  7.47         0.48
12.1731 6.72         0.51
13.2115 4.40         0.58
14.2500 4.07         0.63

In [37]:
f,a,da = np.loadtxt('./data/TestData.txt',skiprows = 3, unpack = True)

__4.__  For the three numpy arrays from the previous problem (`f`, `a`, `da`), write the data out to a data file, including the header ('freq', 'amp', 'error'), with the data displayed in three columns. It's ok if the header lines begin with the `#` comment character. Your new output file name should be "./data/TestDataOut.txt".

In [42]:
heading = 'frequency, amplitude, error'
np.savetxt('./data/TestDataOut.txt',np.array([f,a,da]).T, header = heading, comments ="")

__5.__  For the three numpy arrays from the previous problem (f, a, da), write the data out to a data file to a csv data file, without the header, to a data file ("./data/TestDataOut.csv") with the data displayed in three columns. Use a single format specifier and set it to `"%0.16e"`. If you have access the spreadsheet program (like MS Excel), try opening the file you have created with your Python script and verify that the arrays are displayed in three columns. 

In [56]:
np.savetxt('./data/TestDataOut.txt', np.array([f,a,da]).T, fmt ="%0.1e", delimiter = " ,")
%less ./data/TestDataOut.txt

7.5e-01 ,1.4e+01 ,3.2e-01
1.8e+00 ,1.2e+01 ,9.2e-01
2.8e+00 ,1.4e+01 ,7.3e-01
3.9e+00 ,1.7e+01 ,2.1e+00
4.9e+00 ,2.3e+01 ,1.8e+00
5.9e+00 ,3.5e+01 ,9.1e-01
7.0e+00 ,6.1e+01 ,9.9e-01
8.0e+00 ,3.3e+01 ,3.6e-01
9.1e+00 ,1.8e+01 ,2.3e+00
1.0e+01 ,1.1e+01 ,2.1e-01
1.1e+01 ,7.5e+00 ,4.8e-01
1.2e+01 ,6.7e+00 ,5.1e-01
1.3e+01 ,4.4e+00 ,5.8e-01
1.4e+01 ,4.1e+00 ,6.3e-01


In [14]:
%less ../data/TestDataOut.csv

7.5000000000000000e-01,1.3520000000000000e+01,3.2000000000000001e-01
1.7885000000000000e+00,1.2109999999999999e+01,9.2000000000000004e-01
2.8269000000000002e+00,1.4270000000000000e+01,7.2999999999999998e-01
3.8654000000000002e+00,1.6600000000000001e+01,2.0600000000000001e+00
4.9038000000000004e+00,2.2910000000000000e+01,1.7500000000000000e+00
5.9423000000000004e+00,3.5280000000000001e+01,9.1000000000000003e-01
6.9808000000000003e+00,6.0990000000000002e+01,9.8999999999999999e-01
8.0191999999999997e+00,3.3380000000000003e+01,3.5999999999999999e-01
9.0577000000000005e+00,1.7780000000000001e+01,2.3199999999999998e+00
1.0096200000000000e+01,1.0990000000000000e+01,2.0999999999999999e-01
1.1134600000000001e+01,7.4699999999999998e+00,4.7999999999999998e-01
1.2173100000000000e+01,6.7199999999999998e+00,5.1000000000000001e-01
1.3211499999999999e+01,4.4000000000000004e+00,5.7999999999999996e-01
1.4250000000000000e+01,4.0700000000000003e+00,6.3000000000000000e-01
