## Input and Output

When you have Python perform some task, you need to feed it information---input. 

When it is done with that task, it reports back to you the results of its calculations---output.

## Keyboard input

Python has a function called `input` for getting input from the user and assigning it a variable name. 

In [3]:
strname = input("prompt to user: ")

prompt to user:  dsf


In [4]:
strname

'dsf'

When the `input` statement is executed, it prints the text in the quotes to the computer screen and waits for input from the user. The user types a string of characters and presses the return key. The `input` function then assigns that string to the variable name on the right of the assignment operator `=`.

In [7]:
distance = input("Input distance of trip in miles: ")

Input distance of trip in miles:  450


Python prints out the string argument of the `input` function and waits for a response from you. 

Type `450` for "450 miles" and press return. 

Now type the variable name `distance` to see its value

In [8]:
distance

'450'

The value of the `distance` is `450` as expected, but it is a string. 

Because we want to use `450` as a number, we need to convert it from a string to a number.

In [9]:
distance = eval(distance)

In [10]:
distance

450

The `eval` function has converted `distance` to an integer. However, we might prefer that `distance` be a float instead of an integer. 

In [11]:
distance = input("Input distance of trip in miles: ")

Input distance of trip in miles:  450


In [12]:
distance

'450'

In [13]:
distance = float(distance)

In [14]:
distance

450.0

## Make your code better

In [15]:
# Calculates time, gallons of gas used, and cost of gasoline for a trip
distance = input("Input distance of trip in miles: ")
distance = float(distance)
mpg = 30.
speed = 60.
costPerGallon = 4.10
time = distance / speed
gallons = distance / mpg
cost = gallons * costPerGallon

Input distance of trip in miles:  450


Lines 4 and 5 can be combined into a single line, which is a little more efficient:


```python
distance = float(input("Input distance of trip in miles: "))
```

## Screen output

It would be much more convenient if the program in the previous section would simply write its output to the computer screen, instead of requiring the user to type `time`, `gallons`, and `cost` to view the results. This can be accomplished very simply using Python's `print` function. 

In [16]:
# Calculates time, gallons of gas used, and cost of gasoline for a trip
distance = input("Input distance of trip in miles: ")
distance = float(distance)
mpg = 30.
speed = 60.
costPerGallon = 4.10
time = distance / speed
gallons = distance / mpg
cost = gallons * costPerGallon
print(time, gallons, cost)

Input distance of trip in miles:  450


7.5 15.0 61.49999999999999


The program prints out the results as a tuple of time (in hours), gasoline used (in gallons), and cost (in dollars).

## Formatting output

In [17]:
distance = 450
mpg = 30.
speed = 60.
costPerGallon = 4.10
time = distance/speed
gallons = distance/mpg
cost = gallons*costPerGallon
print("Duration of trip = %d %d hours" % (round(time),int(time))) 
print("Gasoline used = %.1f gallons at %.0f mpg" % (gallons, mpg))
print("Cost of gasoline = %.2f" % cost)

Duration of trip = 8 7 hours
Gasoline used = 15.0 gallons at 30 mpg
Cost of gasoline = 61.50


#### Some notes about $print$
- only information within the "" will be printed
- the '%.1f' means printing out the value with 1 digits, and etc.
- the variables within the () after the % sign will be printed out.
- the number and order of variables must match the number and order of '%' within the ""

## Printing arrays

Formatting NumPy arrays for printing requires another approach. As an example, let's create an array and then format it in various ways. 

In [18]:
import numpy as np

In [19]:
a = np.linspace(3, 19, 7)
print(a)

[ 3.          5.66666667  8.33333333 11.         13.66666667 16.33333333
 19.        ]


Simply using the `print` function does print out the array, but perhaps not in the format you desire. 

To control the output format, you use the NumPy function `set_printoptions`. 

For example, suppose you want to see no more than two digits to the right of the decimal point. Then you simply write

In [20]:
np.set_printoptions(precision=2)

In [21]:
print(a)

[ 3.    5.67  8.33 11.   13.67 16.33 19.  ]


If you want to change the number of digits to the right of the decimal point to 4, you set the keyword argument `precision` to 4

In [22]:
np.set_printoptions(precision=4)

In [23]:
print(a)

[ 3.      5.6667  8.3333 11.     13.6667 16.3333 19.    ]


To return to the default format, type the following

In [24]:
np.set_printoptions(precision=8)

In [25]:
print(a)

[ 3.          5.66666667  8.33333333 11.         13.66666667 16.33333333
 19.        ]


The `set_printoptions` is a NumPy function, so if you use it in a script or program, you should call it by writing `np.set_printoptions`.

## File input

### Reading data from a text file

Often you would like to analyze data that you have stored in a text file. Consider, for example, the data file below for an experiment measuring the free fall of a mass.

In [29]:
%less ./data/MyData.txt

Data for falling mass experiment
Date: 16-Aug-2013
Data taken by Lauren and John

data point      time (sec)      height (mm)     uncertainty (mm)
    0               0               180             3.5
    1               0.5             182             4.5
    2               1               178             4.0
    3               1.5             165             5.5
    4               2               160             2.5
    5               2.5             148             3.0
    6               3               136             2.5
    7               3.5             120             3.0
    8               4                99             4.0
    9               4.5              83             2.5
   10               5                55             3.6
   11               5.5              35             1.75
   12               6                 5             0.75


We would like to read these data into a Python program, associating the data in each column with an appropriately named array. 

While there are a multitude of ways to do this in Python, the simplest by far is to use the NumPy `loadtxt` function. 

Suppose that the name of the text file is `MyData.txt`. Then we can read the data into four different arrays with the following statement

In [30]:
import numpy as np
dataPt, time, height, error = np.loadtxt("./data/MyData.txt", skiprows=5 , unpack=True)

In [31]:
help(np.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
        The char

```python
dataPt, time, height, error = np.loadtxt("./data/MyData.txt", skiprows=5 , unpack=True)
```

Arguments:

1. the name of the file to be read

2. skip the first 5 lines at the top of file, sometimes called the *header*

3. output the data (*unpack* the data) so that it can be directly read into arrays. 

The names labeling the columns in the text file are not used, but you are free to choose the same or similar names, of course, as long as they are legal array names. 

If the file is not under your current folder, you need to specify the directory path with the file name.

It is important that the data file is a *text* file. 

If you don't want to read in all the columns of data, you can specify which columns to read in using the `usecols` key word.

In [36]:
time, height = np.loadtxt('./data/MyData.txt', 
                       skiprows=5 , usecols = (1,2), unpack=True)
time

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [37]:
#if ignore the unpack=True
data= np.loadtxt('./data/MyData.txt', 
                       skiprows=5 , usecols = (1,2))
data

array([[  0. , 180. ],
       [  0.5, 182. ],
       [  1. , 178. ],
       [  1.5, 165. ],
       [  2. , 160. ],
       [  2.5, 148. ],
       [  3. , 136. ],
       [  3.5, 120. ],
       [  4. ,  99. ],
       [  4.5,  83. ],
       [  5. ,  55. ],
       [  5.5,  35. ],
       [  6. ,   5. ]])

reads in only columns 1 and 2; columns 0 and 3 are skipped. 

Only two array names are included to the left of the "`=`" sign, corresponding to the two column that are read.

Writing `usecols = (0,2,3)` would skip column 1 and read in only the data in colums 0, 2, and 3. In this case, 3 array names would need to be provided on the left hand side of the "`=`" sign.

One convenient feature of the `loadtxt` function is that it recognizes any *white space* as a column separator: spaces, tabs, *etc.*

Finally you should remember that `loadtxt` is a NumPy function. So if you are using it in a Python module, you must be sure to include an "`import numpy as np`" statement before calling "`np.loadtxt`".

In [38]:
time #check your reading is correct.

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [40]:
%less ./data/MyData2.txt

0, 0,180,3.5
1,0.5,182,4.5
2,1,178,4.0
3,1.5,165,5.5
4,2,160,2.5
5,2.5,148,3.0
6,3,136,2.5
7,3.5,120,3.0
8,4,99,4.0
9,4.5,83,2.5
10,5,55,3.6
11,5.5,35,1.75
12,6,5,0.75


In [41]:
dataPt, time, height, error = np.loadtxt("./data/MyData2.txt", \
        unpack=True, delimiter=",")
dataPt

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

## Reading data from a CSV file

Sometimes you have data stored in a spreadsheet program like Excel that you would like to read into a Python program. The fig-ExcelWindow shown here contains the same data set we saw above in a text file.
<img src='./figs/ExcelDataFile.png' width=600>

One of the most robust way is to save the spreadsheet as a CSV ("comma separated value") file, a format which all common spreadsheet programs can create and read. 

So, if your Excel spreadsheet was called `MyData.xlsx`, the CSV file saved using Excel's `Save As` command would by default be `MyData.csv`. It would look like this


In [42]:
%less ./data/MyData.csv

Data for falling mass experiment,,,
Date: 6-Apr-2012,,,
Data taken by Lauren and John,,,
,,,
data point,time (sec0,height (mm),uncertainty (mm)
0,0,180,3.5
1,0.5,182,4.5
2,1,178,4
3,1.5,165,5.5
4,2,160,2.5
5,2.5,148,3
6,3,136,2.5
7,3.5,120,3
8,4,99,4
9,4.5,83,2.5
10,5,55,3.6
11,5.5,35,1.75
12,6,5,0.75

The CSV file is simply a text file with the data that was formerly in spreadsheet columns now separated by commas. 

We can read the data in this file into a Python program using the `loadtxt` NumPy function once again. 

In [43]:
dataPt, time, height, error = np.loadtxt("./data/MyData.csv", 
                                      skiprows=5 , unpack=True, delimiter=',')

The form of the function is exactly the same as before except we have added the argument `delimiter=','` that tells `loadtxt` that the columns are separated by commas instead of white space (spaces or tabs), which is the default. 

In [44]:
time

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

## Writing data to a text file

We will use one very simple one that's suitable for writing data files in text format. It uses the NumPy `savetxt` routine, which is the counterpart of the `loadtxt` routine. 

In [45]:
import numpy as np

dataPt, time, height, error = np.loadtxt("./data/MyData.txt", skiprows=5, unpack=True)

np.savetxt('./data/MyDataOut.txt', np.array([dataPt, time, height, error]).T, fmt="%12.1f")

In [48]:
%less ./data/MyDataOut.txt

         0.0          0.0        180.0          3.5
         1.0          0.5        182.0          4.5
         2.0          1.0        178.0          4.0
         3.0          1.5        165.0          5.5
         4.0          2.0        160.0          2.5
         5.0          2.5        148.0          3.0
         6.0          3.0        136.0          2.5
         7.0          3.5        120.0          3.0
         8.0          4.0         99.0          4.0
         9.0          4.5         83.0          2.5
        10.0          5.0         55.0          3.6
        11.0          5.5         35.0          1.8
        12.0          6.0          5.0          0.8



##### np.savetxt(filename, array, fmt="%0.18e", delimiter=" ", newline="\n", header="", footer="", comments="# ")


__1.__ the name of the data file to be created. If there is already a file of that name on your computer, it will be overwritten.

__2.__ the data array the is to be written to the data file. Because we want to write not one but four data arrays to the file, we have to package the four data arrays as one and then transpose to make them column.

Note that the first two arguments, the filename and data array, are regular arguments and thus must appear as the first and second arguments in the correct order. 


##### np.savetxt(filename, array, fmt="%0.18e", delimiter=" ", newline="\n", header="", footer="", comments="# ")


The remaining arguments are all keyword arguments, meaning that they are optional and can appear in any order.

__3.__ a format string that determines how the elements of the array are displayed in the data file. We choose  `12.1f`, which is a float displayed with 1 digit to the right of the decimal point and a minimum width of 12. By choosing 12, which is more digits than any of the numbers in the various arrays have, we ensure that all the columns will have the same width. It also ensures that the decimal points in column of numbers are aligned. 

In [50]:
%less ./data/MyDataOut.txt

         0.0          0.0        180.0          3.5
         1.0          0.5        182.0          4.5
         2.0          1.0        178.0          4.0
         3.0          1.5        165.0          5.5
         4.0          2.0        160.0          2.5
         5.0          2.5        148.0          3.0
         6.0          3.0        136.0          2.5
         7.0          3.5        120.0          3.0
         8.0          4.0         99.0          4.0
         9.0          4.5         83.0          2.5
        10.0          5.0         55.0          3.6
        11.0          5.5         35.0          1.8
        12.0          6.0          5.0          0.8


```python
np.savetxt(filename, array, fmt="%0.18e", delimiter=" ", newline="\n", header="", footer="", comments="# ")
```

__4.__ `delimiter` keyword argument, which leaves the delimiter as the default space.

__5.__ `header` keyword argument, which is a string variable that allows you to write header text above the data. 


In [51]:
import numpy as np

dataPt, time, height, error = np.loadtxt("./data/MyData.txt",
                                 skiprows=5, unpack=True)
info = 'Data for falling mass experiment'
info += 'Date: 16-Aug-2013'
info += '\nData taken by Lauren and John'
info += '\n\n data point time (sec) height (mm) ' 
info += 'uncertainty (mm)'

np.savetxt('./data/MyDataOut.txt', np.array([dataPt, time, height, error]).T, header=info, fmt="%12.1f", comments="")

Now the data file produces has a header preceding the data. Notice that the header rows all start with a `#` comment character, which is the default setting for the `savetxt` function. This can be changed using the keyword argument `comments`. You can find more information about `savetxt` using the IPython `help` function or from the online NumPy documentation.

In [54]:
%less ./data/MyDataOut.txt

Data for falling mass experimentDate: 16-Aug-2013
Data taken by Lauren and John

 data point time (sec) height (mm) uncertainty (mm)
         0.0          0.0        180.0          3.5
         1.0          0.5        182.0          4.5
         2.0          1.0        178.0          4.0
         3.0          1.5        165.0          5.5
         4.0          2.0        160.0          2.5
         5.0          2.5        148.0          3.0
         6.0          3.0        136.0          2.5
         7.0          3.5        120.0          3.0
         8.0          4.0         99.0          4.0
         9.0          4.5         83.0          2.5
        10.0          5.0         55.0          3.6
        11.0          5.5         35.0          1.8
        12.0          6.0          5.0          0.8


## Writing data to a CSV file

To produce a CSV file, you would specify a comma as the delimiter. You might use the `0.1f` format specifier, which leaves no extra spaces between the comma data separators, as the file is to be read by a spreadsheet program, which will determine how the numbers are displayed. The code, which could be substituted for the `savetxt` line in the above code reads.

In [55]:
np.savetxt('./data/MyDataOut.csv', np.array([dataPt, time, height, error]).T, fmt="%0.1f", delimiter=",")

# [Exercise 04](EX04-IO.ipynb)